apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-health-check-2hv7
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-health-check-2hv7
    app.kubernetes.io/part-of: e2e-nodejs
  name: nodejs-health-check-2hv7
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: nodejs-health-check-2hv7
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: nodejs-health-check-2hv7
    spec:
      containers:
      - image: quay.io/rh-gitops-bot/rhtap-demo-prxd-tenant/e2e-nodejs/nodejs-health-check-2hv7@sha256:caa3d0801f9c9fa38102487d794527996bfc0a251133141e5977ad6138ae01f3
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
